spring:
  application:
    name: XCity
  data:
    mongodb:
      uri: ${MONGO_URL}

app:
  token:
    secret: ${AUTH_SECRET_KEY}
    expirationTime: 200000
  ai-server: ${AI_SERVER_URL}
  overpass-url: https://overpass-api.de/api/interpreter
  orion-url: ${ORION-LD-URL}
  client-url: ${CLIENT-URL}

server:
  port: 8080
  servlet:
    context-path: /xcity-service
