spring:
  application:
    name: XCity
  data:
    mongodb:
      uri: ${MONGO_URL}

app:
  token:
    secret: ${AUTH_SECRET_KEY}
    expirationTime: 200000
  ai-server: ${AI_SERVER_URL}
  overpass-url: https://overpass-api.de/api/interpreter
  orion-url: ${ORION_LD_URL}
  client-url: ${CLIENT_URL}
  sensor-url: ${SENSOR_SERVICE}
  iot-agent-url: ${IOT_AGENT}

server:
  port: 8080
  servlet:
    context-path: /xcity-service
